### ISSUE TITLE
scraperwiki.sqlite.save() doesn't coerce dictionaries/lists into string representations

### ISSUE THREAD

**Issue by zarino** [scraperwiki/scraperwiki-python#21]
This code works in Classic:

```python
import scraperwiki
d = {"name": {"first_name":"zarino", "last_name":"zappia"}, "age": 24, "id": 1}
scraperwiki.sqlite.save(['id'], d)
```

But it raises an exception in scraperwiki-python:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/scraperwiki/sqlite.py", line 34, in save
    return dt.upsert(data, table_name = table_name)
  File "/Library/Python/2.7/site-packages/dumptruck/dumptruck.py", line 301, in upsert
    self.insert(upsert=True, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/dumptruck/dumptruck.py", line 284, in insert
    self.execute(sql, values, commit=False)
  File "/Library/Python/2.7/site-packages/dumptruck/dumptruck.py", line 138, in execute
    raise self.sqlite3.InterfaceError(unicode(msg) + '\nTry converting types or pickling.')
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.
Try converting types or pickling.
```

ScraperWiki Classic used to call `repr()` or something on cell values that aren't strings, integers, floats or nones; scraperwiki-python does not. This is a bug, since scraperwiki-python is meant to replicate Classic as closely as possible.

**Comment by drj11** [comment]
not gonna happen now.

**Comment by codecakes** [comment]
+1 on this issue. effectively i want to be able to save whatever primitive python structure ive to sqlite. I suggest those structure be instead converted using `json.dumps`

**Comment by drj11** [comment]
What are you trying to achieve and what are you doing to workaround this issue?

**Comment by codecakes** [comment]
> What are you trying to achieve and what are you doing to workaround this issue?

similar to https://github.com/sensiblecodeio/scraperwiki-python/issues/21#issue-14512808
