### ISSUE TITLE
Not Python 3 compatible

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/scraperwiki-python#81]

**Comment by drj11** [comment]
An interim approach that I did with https://github.com/drj11/pypng is to keep the code as Python 2 code, but make sure it runs through `2to3` cleanly. `distribute` has some support for doing this automagically in `setup.py` (when run on Python3).

**Comment by StevenMaude** [comment]
Thanks @drj11 for the tip; might ask you for guidance if I get stuck with it.

**Comment by scraperdragon** [comment]
https://github.com/scraperwiki/scraperwiki-python/pull/83

**Comment by drj11** [comment]
The approach we are taking in #83 is to make the same code be both Python 2 and Python 3 compatible (this is not too bad if you target the most recent versions of both Python 2 and Python 3).

**Comment by pwaller** [comment]
Is this resolved @scraperdragon?

**Comment by StevenMaude** [comment]
This is done; PR was merged a while ago.
