### ISSUE TITLE
sqlalchemy.exc.OperationalError on writing to a table `details`

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/scraperwiki-python#88]
As described in this issue:

https://bitbucket.org/scraperwikids/contract-finder/issues/2/sqlalchemyexcoperationalerror-for-most

This scraper fails on:
```
scraperwiki.sqlite.save(
            unique_keys=['URL'],
            data=record,
            table_name='details')
```

For version 0.5.1 with an error that begins:

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: details [SQL:`

**Comment by pwaller** [comment]
This usually means out of disk or a misnamed or corrupted file or something like that, in my experience. Can you give more detail? Is there any more information available?

**Comment by pwaller** [comment]
Is the bug reproducible, and can you reproduce it in more than one place?

**Comment by IanHopkinson** [comment]
I've reproduced the bug in multiple boxes on the platform. I'll try to reproduce on my Windows machine and make a minimal failing case.

**Comment by pwaller** [comment]
Ah, the interesting part is `sqlalchemy.exc.OperationalError: no such table` (missed from the issue title and body). Then we need to figure out why table creation isn't happening.

**Comment by IanHopkinson** [comment]
I was running the database writes inside a `dshelpers` batchprocessor when I disabled the batchprocessor I revealed a different error - I had specified columns with names `Date_scraped` and `date_scraped` which sqlalchemy identified as duplicates. Fixing this and re-applying the batchprocessor seems to have resolved the original problem.
