### ISSUE TITLE
Dependency on pdftohtml

### ISSUE THREAD

**Issue by hassaananjum** [scraperwiki/scraperwiki-python#91]
The method pdftoxml is dependent on the utility pdftohtml. If the utility is missing, no error is reported but no xml is returned either on calling the method on pdf file data. To fix the problem pdftohtml needs to be installed which is part of poppler-utils. So run `sudo apt-get install poppler-utils`. The devs need to update the `Readme` file for dependencies.

**Comment by StevenMaude** [comment]
Thanks for reporting :+1:

**Comment by navulurinaresh** [comment]
Thanks a lot. Working perfectly
